name: check

on:
  push:

jobs:
  check:
    name: lint and typecheck

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint code with ESLint and stylelint
        run: yarn lint

      - name: Check static types with TypeScript
        run: yarn typecheck
