name: lint, typecheck and test

on: push

jobs:
  checkup:
    name: lint, typecheck, test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: run eslint and stylelint
        run: yarn lint

      - name: run static types check
        run: yarn typecheck
      
      - name: count lines of code
        uses: djdefi/cloc-action@main
