name: lint and static typecheck

on: push

jobs:
  checkup:
    name: lint and static typecheck
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: run eslint and stylelint
        run: yarn lint

      - name: run static types check
        run: yarn typecheck

      - name: count lines of code
        run: |
          yarn global add cloc
          cloc src/
 
        
